image: ritproject/cli:docker
services:
  - docker:dind
variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - test
  - update project images
  - update production images
  - deploy
before_script:
  - rit --log on_error config tunnel add repo https://github.com/altjohndev/tunnel-workspace --name workspace
  - rit --log on_error config tunnel default set workspace

# Stage: test

test:
  stage: test
  variables:
    COMPOSE_DOCKERFILE_BUILD_TYPE: recursive
  script:
    - rit --log on_error tunnel --input disabled run my website test build
    - rit --log on_error tunnel --input disabled run my website test up
    - rit --log on_error tunnel --input disabled run my website test exec
  only:
    changes:
      - '**/*.{eex,ex,exs,leex,po,pot,yml}'
      - assets/**/*
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /--do-not-trigger-ci/
      - $CI_COMMIT_MESSAGE =~ /--skip-stage-test/
      - $CI_COMMIT_MESSAGE =~ /--skip-job-test/
  tags:
    - docker

# Stage: update project images

.update_project_image: &update_project_image
  stage: update project images
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /--update-project-images/
  tags:
    - docker

update development image:
  <<: *update_project_image
  script:
    - rit --log on_error tunnel --input disabled run my website development build
    - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
    - rit --log on_error tunnel --input disabled run my website development push

update test image:
  <<: *update_project_image
  script:
    - rit --log on_error tunnel --input disabled run my website test build
    - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
    - rit --log on_error tunnel --input disabled run my website test push

update release image:
  <<: *update_project_image
  script:
    - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
    - rit --log on_error tunnel --input disabled run my website release build
    - rit --log on_error tunnel --input disabled run my website release push

# Stage: update production images

.update_production_image: &update_production_image
  stage: update production images
  script:
    - rit --log on_error tunnel --input disabled run my website release build
    - rit --log on_error tunnel --input disabled run my website production build
    - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
    - rit --log on_error tunnel --input disabled run my website production push
  tags:
    - docker

update unstable image:
  <<: *update_production_image
  variables:
    COMPOSE_DOCKERFILE_BUILD_TYPE: recursive
    COMPOSE_IMAGE_TAG: unstable
  environment:
    name: unstable
  only:
    changes:
      - '**/*.{eex,ex,exs,leex,po,pot,yml}'
      - assets/**/*
    refs:
      - /^develop$/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /--do-not-trigger-ci/
      - $CI_COMMIT_MESSAGE =~ /--skip-stage-update-production-image/
      - $CI_COMMIT_MESSAGE =~ /--skip-job-update-unstable-image/

update production image:
  <<: *update_production_image
  variables:
    COMPOSE_DOCKERFILE_BUILD_TYPE: recursive
    COMPOSE_IMAGE_TAG: production
  environment:
    name: production
  only:
    changes:
      - '**/*.{eex,ex,exs,leex,po,pot,yml}'
      - assets/**/*
    refs:
      - /^master$/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /--do-not-trigger-ci/
      - $CI_COMMIT_MESSAGE =~ /--skip-stage-update-production-image/
      - $CI_COMMIT_MESSAGE =~ /--skip-job-update-production-image/

deploy production:
  stage: deploy
  environment:
    name: production
  script:
    - rit --log on_error tunnel --input disabled run my website production deploy pull
    - rit --log on_error tunnel --input disabled run my website production deploy up
    - rit --log on_error tunnel --input disabled run my website production deploy sync
    - rit --log on_error tunnel --input disabled run my website production deploy playbook
  only:
    changes:
      - '**/*.{eex,ex,exs,leex,po,pot,yml}'
      - assets/**/*
    refs:
      - /^master$/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /--do-not-trigger-ci/
      - $CI_COMMIT_MESSAGE =~ /--skip-stage-deploy/
      - $CI_COMMIT_MESSAGE =~ /--skip-job-deploy-production/
  tags:
    - docker
